media:
  input: src/assets
  output: /assets

content:
  - name: authors
    label: Authors
    type: collection
    path: src/data/authors
    view:
      fields: [name, bio]
    fields:
      - name: name
        label: Name
        type: string
      - name: avatar
        label: Avatar
        type: image
      - name: bio
        label: Bio
        type: text

  - name: site_info
    label: Site Information
    type: file
    path: src/data/site/info.md
    fields:
      - name: siteLogo
        label: Site Logo
        type: image
        description: Site logo

      - name: seo
        label: SEO Settings
        type: object
        fields:
          - name: siteTitle
            label: Site Title
            type: string
          - name: siteDescription
            label: Site Description
            type: text
          - name: siteKeywords
            label: Site Keywords
            type: string

      - name: menu
        label: Menu
        type: object
        list: true
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: string

      - name: heroSection
        label: Hero Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: text
          - name: primaryButtonText
            label: Primary Button Text
            type: string
          - name: secondaryButtonText
            label: Secondary Button Text
            type: string

      - name: whyTrustSection
        label: Why Trust Section
        type: object
        fields:
          - name: sectionTitle
            label: Section Title
            type: string
            default: Why Trust Our Casino Reviews?
          - name: trustCards
            label: Trust Cards
            type: object
            list: true
            fields:
              - name: title
                label: Card Title
                type: string
              - name: description
                label: Card Description
                type: text
              - name: iconSvg
                label: Card Icon SVG
                type: text
                description: Paste the SVG code here

      - name: body
        label: Content
        type: rich-text

  - name: casinos
    label: Casinos
    type: collection
    path: src/data/casinos
    view:
      fields: [basic.name, basic.rating, basic.established]
    fields:
      - name: basic
        label: Basic Information
        type: object
        fields:
          - name: cover
            label: Cover Image
            type: image
          - name: name
            label: Casino Name
            type: string
          - name: description
            label: Casino Description
            type: text
          - name: established
            label: Established
            type: string
          - name: website
            label: Website
            type: string
          - name: owner
            label: Owner
            type: string
          - name: license
            label: License
            type: string
          - name: rating
            label: Rating
            type: number
            options:
              min: 1
              max: 5
          - name: bonus
            label: Bonus
            type: string

      - name: secondary
        label: Secondary Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: text

      - name: financialInfo
        label: Financial Information
        type: object
        fields:
          - name: minimumDeposit
            label: Minimum Deposit
            type: string
          - name: minimumWithdrawal
            label: Minimum Withdrawal
            type: string
          - name: gameCount
            label: Game Count
            type: string

      - name: author
        label: Author
        type: reference
        options:
          collection: authors
          search: "name,bio"
          value: "{name}"
          label: "{name}"
          image: "{avatar}"

      - name: depositMethods
        label: Deposit Methods
        type: object
        list: true
        fields:
          - name: name
            label: Method Name
            type: string
          - name: code
            label: Method Code
            type: string

      - name: withdrawalMethods
        label: Withdrawal Methods
        type: object
        list: true
        fields:
          - name: name
            label: Method Name
            type: string
          - name: code
            label: Method Code
            type: string

      - name: games
        label: Games
        type: object
        list: true
        fields:
          - name: name
            label: Game Name
            type: string
          - name: icon
            label: Game Icon
            type: string
          - name: available
            label: Available
            type: boolean
            default: true

      - name: body
        label: Content
        type: rich-text
